name: Update README

on:
  schedule:
    - cron: "0 0 * * *"   # Runs once daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README stats
        run: |
          echo "No build needed — dynamic widgets auto-refresh"